# Generated by Django 4.2.6 on 2023-10-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confession',
            old_name='content',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='confession',
            name='timestamp',
        ),
    ]
