# Generated by Django 4.2.6 on 2023-10-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='confession',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='confession',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
